---
# Example ESPHome configuration for Cosori Kettle BLE
#
# This configuration demonstrates how to integrate a Cosori smart kettle
# with Home Assistant via ESPHome and BLE.
#
# Hardware: ESP32 board with Bluetooth LE support
#
# Setup:
# 1. Find your kettle's MAC address using BLE scanner app or `bluetoothctl`
# 2. Update the mac_address substitution below
# 3. Flash this configuration to your ESP32
# 4. Add to Home Assistant

substitutions:
  device_name: cosori-kettle
  friendly_name: "Cosori Kettle"
  # Replace with your kettle's MAC address
  kettle_mac_address: "C4:A9:B8:73:AB:29"

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging (optional: set to WARN or ERROR in production)
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

# BLE Client for the kettle
ble_client:
  - mac_address: ${kettle_mac_address}
    id: cosori_kettle_client
    # Auto-connect on startup
    auto_connect: true

# External component from GitHub
external_components:
  - source: github://barrymichels/CosoriKettleBLE
    components: [cosori_kettle_ble]
    refresh: 0s

# Cosori Kettle BLE Component
cosori_kettle_ble:
  ble_client_id: cosori_kettle_client
  id: my_cosori_kettle
  name: "${friendly_name} Temperature Control"  # Sets the climate entity name
  update_interval: 10s
  protocol_version: 1 # 0 or 1 - depends on kettle
  registration_key: '9802e91afc3bca8f9c71cba5127e7d5f' # random 16-byte key OR key pulled from your device

# ============================================================================
# Climate Entity (Thermostat Card Support)
# ============================================================================
# The kettle automatically appears as a climate entity!
# You can use Home Assistant's native thermostat card:
#
# type: thermostat
# entity: climate.cosori_kettle_temperature_control
#
# This provides:
# - Semi-circle temperature slider (104-212°F)
# - Current temperature display
# - Mode control (OFF / HEAT)
# - Action indicator (IDLE / HEATING)
#
# The climate entity is created automatically - no additional configuration needed!
# It works alongside the individual entities below for maximum flexibility.

# ============================================================================
# Sensors (read-only status information)
# ============================================================================
sensor:
  - platform: cosori_kettle_ble
    cosori_kettle_ble_id: my_cosori_kettle

    # Current water temperature
    temperature:
      name: "${friendly_name} Temperature"
      id: kettle_temp
      filters:
        # Optional: Convert to Celsius
        # - lambda: return (x - 32) * 5.0 / 9.0;
        # - or:
        #   - multiply: 0.556
        #   - offset: -17.78
        # If converting to Celsius, change unit_of_measurement to "°C"

    # Actual setpoint configured on the kettle
    kettle_setpoint:
      name: "${friendly_name} Kettle Setpoint"
      id: kettle_sp

# ============================================================================
# Binary Sensors (on/off status indicators)
# ============================================================================
binary_sensor:
  - platform: cosori_kettle_ble
    cosori_kettle_ble_id: my_cosori_kettle

    # Is the kettle on its base?
    on_base:
      name: "${friendly_name} On Base"

    # Is the kettle actively heating?
    heating:
      name: "${friendly_name} Heating"

# ============================================================================
# Number Input (target temperature control)
# ============================================================================
number:
  - platform: cosori_kettle_ble
    cosori_kettle_ble_id: my_cosori_kettle

    # User-adjustable target setpoint (104-212°F)
    target_setpoint:
      name: "${friendly_name} Target Temperature"
      id: target_temp
      mode: box  # or "slider"
    hold_time:
      name: "Hold Time"
    my_temp:
      name: "My Temperature"

# ============================================================================
# Switches (control actions)
# ============================================================================
switch:
  - platform: cosori_kettle_ble
    cosori_kettle_ble_id: my_cosori_kettle

    # Start/stop heating
    heating_switch:
      name: "${friendly_name} Heating"
      id: heating_control
      icon: "mdi:kettle"
      # When turned ON: sends target_setpoint to kettle and starts heating
      # When turned OFF: stops heating

    # Enable/disable BLE connection
    ble_connection_switch:
      name: "${friendly_name} BLE Connection"
      id: ble_control
      restore_mode: RESTORE_DEFAULT_ON
      # Turn OFF to disconnect and allow official mobile app to connect
      # (Kettle only allows one BLE connection at a time)

    baby_formula_switch:
      name: "Baby Formula Mode"

    # Register/pair with kettle (requires device to be in pairing mode)
    register_switch:
      name: "${friendly_name} Register"
      id: register_sw
      icon: "mdi:key-plus"
      # Enable to send registration command (0x80) to pair with kettle
      # Device must be in pairing mode for this to work
      # After successful registration, switch automatically turns off
      # Disable to send hello command (0x81) for reconnection

# ============================================================================
# Home Assistant Dashboard Examples
# ============================================================================
# Option 1: Thermostat Card (Recommended - Beautiful semi-circle slider!)
#
# type: thermostat
# entity: climate.cosori_kettle_temperature_control
#
# This gives you:
# - Beautiful semi-circle temperature slider
# - Current temperature display
# - OFF/HEAT mode toggle
# - IDLE/HEATING action indicator
#
# Option 2: Individual Entities Card
#
# type: entities
# title: Cosori Kettle
# entities:
#   - entity: sensor.cosori_kettle_temperature
#   - entity: binary_sensor.cosori_kettle_on_base
#   - entity: binary_sensor.cosori_kettle_heating
#   - entity: number.cosori_kettle_target_temperature
#   - entity: switch.cosori_kettle_heating
#   - entity: switch.cosori_kettle_ble_connection
#   - entity: switch.cosori_kettle_register

# ============================================================================
# Home Assistant Automations Example
# ============================================================================
# Example 1: Notify when kettle reaches temperature
#
# automation:
#   - alias: "Kettle Ready Notification"
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.cosori_kettle_heating
#         from: "on"
#         to: "off"
#     condition:
#       - condition: state
#         entity_id: binary_sensor.cosori_kettle_on_base
#         state: "on"
#     action:
#       - service: notify.mobile_app
#         data:
#           message: "Your kettle is ready! ☕"
#
# Example 2: Start kettle at specific time
#
# automation:
#   - alias: "Morning Kettle"
#     trigger:
#       - platform: time
#         at: "07:00:00"
#     condition:
#       - condition: state
#         entity_id: binary_sensor.cosori_kettle_on_base
#         state: "on"
#     action:
#       - service: number.set_value
#         target:
#           entity_id: number.cosori_kettle_target_temperature
#         data:
#           value: 212
#       - service: switch.turn_on
#         target:
#           entity_id: switch.cosori_kettle_heating
